#!/usr/bin/env python3
# Real-Time Routing Table Analysis using MCP Resources | WMN Course Project | May 2026
"""
routing_poller.py — Polls routing tables from multiple sources.

Priority order:
  1. network/routing_tables.json (generated by Mininet) — if recent (<30s)
  2. 'ip route show' system command
  3. Mock data fallback

Each route dict has the format:
  {destination, gateway, interface, metric, router_id, timestamp}
"""

import subprocess
import json
import time
import os
import random
import threading
from datetime import datetime


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_THIS_DIR)
ROUTING_TABLES_JSON = os.path.join(_PROJECT_ROOT, "network", "routing_tables.json")

# How old (seconds) routing_tables.json can be before we stop trusting it
FRESHNESS_THRESHOLD = 30

# ---------------------------------------------------------------------------
# Mock / simulated routing data
# ---------------------------------------------------------------------------
MOCK_ROUTES = {
    "r1": [
        {"destination": "10.0.1.0/24", "gateway": "", "interface": "r1-eth0", "metric": 0},
        {"destination": "10.0.2.0/24", "gateway": "10.0.1.2", "interface": "r1-eth0", "metric": 0},
        {"destination": "10.0.3.0/24", "gateway": "10.0.4.1", "interface": "r1-eth1", "metric": 0},
        {"destination": "10.0.4.0/24", "gateway": "", "interface": "r1-eth1", "metric": 0},
    ],
    "r2": [
        {"destination": "10.0.1.0/24", "gateway": "", "interface": "r2-eth0", "metric": 0},
        {"destination": "10.0.2.0/24", "gateway": "", "interface": "r2-eth1", "metric": 0},
        {"destination": "10.0.3.0/24", "gateway": "10.0.2.2", "interface": "r2-eth1", "metric": 0},
        {"destination": "10.0.4.0/24", "gateway": "10.0.1.1", "interface": "r2-eth0", "metric": 0},
    ],
    "r3": [
        {"destination": "10.0.1.0/24", "gateway": "10.0.2.1", "interface": "r3-eth0", "metric": 0},
        {"destination": "10.0.2.0/24", "gateway": "", "interface": "r3-eth0", "metric": 0},
        {"destination": "10.0.3.0/24", "gateway": "", "interface": "r3-eth1", "metric": 0},
        {"destination": "10.0.4.0/24", "gateway": "10.0.3.2", "interface": "r3-eth1", "metric": 0},
    ],
    "r4": [
        {"destination": "10.0.1.0/24", "gateway": "10.0.4.2", "interface": "r4-eth1", "metric": 0},
        {"destination": "10.0.2.0/24", "gateway": "10.0.3.1", "interface": "r4-eth0", "metric": 0},
        {"destination": "10.0.3.0/24", "gateway": "", "interface": "r4-eth0", "metric": 0},
        {"destination": "10.0.4.0/24", "gateway": "", "interface": "r4-eth1", "metric": 0},
    ],
}

# Network topology definition (ring)
TOPOLOGY = {
    "routers": ["r1", "r2", "r3", "r4"],
    "links": [
        {"from": "r1", "to": "r2", "subnet": "10.0.1.0/24", "from_ip": "10.0.1.1", "to_ip": "10.0.1.2"},
        {"from": "r2", "to": "r3", "subnet": "10.0.2.0/24", "from_ip": "10.0.2.1", "to_ip": "10.0.2.2"},
        {"from": "r3", "to": "r4", "subnet": "10.0.3.0/24", "from_ip": "10.0.3.1", "to_ip": "10.0.3.2"},
        {"from": "r4", "to": "r1", "subnet": "10.0.4.0/24", "from_ip": "10.0.4.1", "to_ip": "10.0.4.2"},
    ],
    "type": "ring",
}


# ---------------------------------------------------------------------------
# Helper: add router_id and timestamp to each route entry
# ---------------------------------------------------------------------------
def _enrich_routes(routes: list[dict], router_id: str) -> list[dict]:
    """Add router_id and timestamp to each route dict."""
    ts = datetime.now().isoformat()
    enriched = []
    for r in routes:
        entry = dict(r)
        entry["router_id"] = router_id
        entry["timestamp"] = ts
        # Normalise empty gateway
        if not entry.get("gateway"):
            entry["gateway"] = "directly connected"
        enriched.append(entry)
    return enriched


# ---------------------------------------------------------------------------
# Source 1: Read from routing_tables.json (Mininet-generated)
# ---------------------------------------------------------------------------
def _read_routing_json() -> dict[str, list[dict]] | None:
    """Read routing_tables.json if it exists and is fresh (< FRESHNESS_THRESHOLD)."""
    if not os.path.exists(ROUTING_TABLES_JSON):
        return None

    age = time.time() - os.path.getmtime(ROUTING_TABLES_JSON)
    if age > FRESHNESS_THRESHOLD:
        return None

    try:
        with open(ROUTING_TABLES_JSON, "r") as f:
            data = json.load(f)
        # data is { "r1": [...], "r2": [...], ... }
        if isinstance(data, dict) and data:
            return data
    except (json.JSONDecodeError, OSError):
        pass
    return None


def _read_routing_json_any_age() -> dict[str, list[dict]] | None:
    """Read routing_tables.json regardless of age."""
    if not os.path.exists(ROUTING_TABLES_JSON):
        return None
    try:
        with open(ROUTING_TABLES_JSON, "r") as f:
            data = json.load(f)
        if isinstance(data, dict) and data:
            return data
    except (json.JSONDecodeError, OSError):
        pass
    return None


# ---------------------------------------------------------------------------
# Source 2: ip route show (system)
# ---------------------------------------------------------------------------
def _parse_ip_route_line(line: str) -> dict | None:
    """Parse a single line of 'ip route show' output."""
    parts = line.strip().split()
    if not parts:
        return None

    route: dict = {
        "destination": parts[0],
        "gateway": "directly connected",
        "interface": "unknown",
        "metric": 0,
    }

    i = 1
    while i < len(parts):
        token = parts[i]
        if token == "via" and i + 1 < len(parts):
            route["gateway"] = parts[i + 1]
            i += 2
        elif token == "dev" and i + 1 < len(parts):
            route["interface"] = parts[i + 1]
            i += 2
        elif token == "metric" and i + 1 < len(parts):
            try:
                route["metric"] = int(parts[i + 1])
            except ValueError:
                route["metric"] = 0
            i += 2
        else:
            i += 1
    return route


def _poll_system_routes() -> list[dict] | None:
    """Run 'ip route show' and parse the output."""
    try:
        result = subprocess.run(
            ["ip", "route", "show"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode != 0:
            return None
        routes = []
        for line in result.stdout.strip().splitlines():
            parsed = _parse_ip_route_line(line)
            if parsed:
                routes.append(parsed)
        return routes if routes else None
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def poll_all_routers() -> dict[str, list[dict]]:
    """Return routing tables for ALL routers (multi-router).

    Priority: routing_tables.json (fresh) → routing_tables.json (any age) → mock.
    Returns: { "r1": [ {route}, ... ], "r2": [...], ... }
    """
    # 1. Try fresh JSON from Mininet
    data = _read_routing_json()
    if data:
        source = "routing_tables.json (live)"
    else:
        # 2. Try any-age JSON
        data = _read_routing_json_any_age()
        if data:
            source = "routing_tables.json (cached)"
        else:
            # 3. Mock fallback
            data = {k: [dict(r) for r in v] for k, v in MOCK_ROUTES.items()}
            source = "mock data"

    # Enrich with router_id and timestamp
    result = {}
    for router_id, routes in data.items():
        result[router_id] = _enrich_routes(routes, router_id)

    return result


def poll_routing_table() -> list[dict]:
    """Return a flat list of ALL routes across ALL routers.

    This maintains backward compatibility with the original API.
    """
    all_routers = poll_all_routers()
    flat = []
    for router_id, routes in sorted(all_routers.items()):
        flat.extend(routes)
    return flat


def poll_single_router(router_id: str) -> list[dict]:
    """Return routing table for a specific router."""
    all_routers = poll_all_routers()
    if router_id in all_routers:
        return all_routers[router_id]
    return []


def get_topology() -> dict:
    """Return the network topology definition."""
    return dict(TOPOLOGY)


def get_data_source_info() -> dict:
    """Return info about the current data source."""
    json_exists = os.path.exists(ROUTING_TABLES_JSON)
    json_age = None
    if json_exists:
        json_age = round(time.time() - os.path.getmtime(ROUTING_TABLES_JSON), 1)

    return {
        "routing_tables_json": ROUTING_TABLES_JSON,
        "json_exists": json_exists,
        "json_age_seconds": json_age,
        "json_fresh": json_exists and json_age is not None and json_age < FRESHNESS_THRESHOLD,
        "freshness_threshold": FRESHNESS_THRESHOLD,
    }


# ---------------------------------------------------------------------------
# File watcher: detect changes to routing_tables.json
# ---------------------------------------------------------------------------
class RoutingFileWatcher:
    """Polls routing_tables.json for changes and triggers a callback."""

    def __init__(self, callback=None, interval: float = 5.0):
        self._callback = callback
        self._interval = interval
        self._last_mtime: float = 0.0
        self._running = False
        self._thread: threading.Thread | None = None

    def start(self):
        """Start watching in a background thread."""
        self._running = True
        self._thread = threading.Thread(target=self._watch_loop, daemon=True)
        self._thread.start()

    def stop(self):
        """Stop the watcher."""
        self._running = False
        if self._thread:
            self._thread.join(timeout=self._interval + 1)

    def _watch_loop(self):
        while self._running:
            try:
                if os.path.exists(ROUTING_TABLES_JSON):
                    mtime = os.path.getmtime(ROUTING_TABLES_JSON)
                    if mtime != self._last_mtime and self._last_mtime > 0:
                        # File changed!
                        if self._callback:
                            self._callback(ROUTING_TABLES_JSON, mtime)
                    self._last_mtime = mtime
            except OSError:
                pass
            time.sleep(self._interval)


def watch_routing_file(callback=None, interval: float = 5.0) -> RoutingFileWatcher:
    """Start watching routing_tables.json for changes.

    Args:
        callback: function(filepath, mtime) called when file changes.
        interval: poll interval in seconds.

    Returns:
        RoutingFileWatcher instance (call .stop() to end).
    """
    watcher = RoutingFileWatcher(callback=callback, interval=interval)
    watcher.start()
    return watcher


# ---------------------------------------------------------------------------
# Standalone test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    print("=" * 60)
    print("  Routing Poller — Standalone Test")
    print("=" * 60)

    # Show data source info
    info = get_data_source_info()
    print(f"\n📂 Data source info:")
    print(f"   JSON path:   {info['routing_tables_json']}")
    print(f"   JSON exists:  {info['json_exists']}")
    print(f"   JSON age:     {info['json_age_seconds']}s")
    print(f"   JSON fresh:   {info['json_fresh']}")

    # Poll all routers
    print(f"\n{'─' * 60}")
    print("📡 Polling all routers …\n")
    all_data = poll_all_routers()
    for router_id, routes in sorted(all_data.items()):
        print(f"  🔹 {router_id}: {len(routes)} routes")
        for r in routes:
            gw = f" via {r['gateway']}" if r['gateway'] != 'directly connected' else ""
            print(f"     {r['destination']}{gw} dev {r['interface']}")
        print()

    # Test single router
    print(f"{'─' * 60}")
    print("📡 Single router poll (r1):")
    r1 = poll_single_router("r1")
    print(json.dumps(r1, indent=2))

    # Test topology
    print(f"\n{'─' * 60}")
    print("🗺️  Topology:")
    print(json.dumps(get_topology(), indent=2))

    # Test flat list (backward compat)
    print(f"\n{'─' * 60}")
    flat = poll_routing_table()
    print(f"📡 Flat route list: {len(flat)} total routes")

    # Test file watcher (brief)
    print(f"\n{'─' * 60}")
    print("👁️  Starting file watcher (5s test) …")

    def on_change(path, mtime):
        print(f"   ⚡ File changed: {path} at {datetime.fromtimestamp(mtime).isoformat()}")

    watcher = watch_routing_file(callback=on_change, interval=2.0)
    time.sleep(5)
    watcher.stop()
    print("   Watcher stopped.")

    print("\n✅ Poller test complete.")
